### ISSUE TITLE
Unable to connect to WebSocket

### ISSUE THREAD

**Issue by te4-adrian-almetun-smeds** [itggot-adrian-almetunsmeds/magic-mirror-gosu#2]
Unable to connect to WebSocket, due to missing cookie in handshake header.

#### Solution:

1. Retrieve session cookie by emulating a sign in to ``localhost:9292/login``.
2. Pass the retrieved session cookie after sign in to WebSocket connect method.

Number 1. Would make use of implementing #1

**Comment by adr29truck** [comment]
See if this can provide some insight into the problem [Faye-websocket-ruby](https://github.com/faye/faye-websocket-ruby/blob/master/lib/faye/eventsource.rb)

**Comment by te4-adrian-almetun-smeds** [comment]
Related to #6

**Comment by te4-adrian-almetun-smeds** [comment]
Solved using token-based identification.
